/**
 * Capture details recovered from the original silverspringastro.com per-image pages
 * (via the Wayback Machine). Keyed by image file name without extension.
 * Generated by scraper/parse_capture_details.py; edit by hand for corrections.
 */

import { CaptureDetails } from '@/lib/types';

export const captureDetails: Record<string, CaptureDetails> = {
  "Abell-1656_LRGB_H85": {
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-04-05",
    "exposures": [
      { "filter": "L", "minutes": 600 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ],
    "notes": [
      "Coma Galaxy Cluster (400 million LY, mag 17 and one mag 19.7 2.1 bLY)"
    ]
  },
  "Abell-262_L_H85": {
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "Abell-426_L_H85": {
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-07-15",
    "exposures": [
      { "filter": "L", "minutes": 120 }
    ],
    "notes": [
      "NGC 1275 (Perseus A)"
    ]
  },
  "Abell262_LRGB_BBO": {
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-11-07",
    "exposures": [
      { "filter": "L", "minutes": 300 },
      { "filter": "R", "minutes": 90 },
      { "filter": "G", "minutes": 90 },
      { "filter": "B", "minutes": 90 }
    ]
  },
  "Arp319_LRGB_BBO": {
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-09-05",
    "exposures": [
      { "filter": "L", "minutes": 400 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ],
    "notes": [
      "Stephan's Quintet"
    ]
  },
  "Arp319_L_H85": {
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-10-02",
    "exposures": [
      { "filter": "L", "minutes": 300 }
    ],
    "notes": [
      "Stephan's Quintet"
    ]
  },
  "Arp319_RGB_H85": {
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-10-02",
    "exposures": [
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ],
    "notes": [
      "Stephan's Quintet"
    ]
  },
  "M100_LRGB_BBO": {
    "ra": "12h22.9m",
    "dec": "+15°49'",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2006-03-26",
    "exposures": [
      { "filter": "L", "minutes": 300 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 36 },
      { "filter": "B", "minutes": 72 }
    ]
  },
  "M101_LRGB_H85": {
    "ra": "14h03.2m",
    "dec": "+54°20'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "M105_L_H85": {
    "ra": "10h47.8m",
    "dec": "+12°34'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-01-18",
    "exposures": [
      { "filter": "L", "minutes": 300 }
    ]
  },
  "M106_LRGB_H85": {
    "ra": "12h19.0m",
    "dec": "+47°18'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-04-10",
    "exposures": [
      { "filter": "L", "minutes": 600 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ]
  },
  "M13_LRGB_H85": {
    "ra": "16h41.7m",
    "dec": "+36°27'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-05-15",
    "exposures": [
      { "filter": "L", "minutes": 120 },
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ]
  },
  "M1_LRGB_H85": {
    "ra": "05h34.5m",
    "dec": "+22°01'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-12-15",
    "exposures": [
      { "filter": "L", "minutes": 120 },
      { "filter": "R", "minutes": 40 },
      { "filter": "G", "minutes": 40 },
      { "filter": "B", "minutes": 40 }
    ]
  },
  "M20_RGB_BBO": {
    "ra": "18h02.5m",
    "dec": "-21°03'",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-12-10",
    "exposures": [
      { "filter": "L", "minutes": 120 },
      { "filter": "R", "minutes": 75 },
      { "filter": "G", "minutes": 45 },
      { "filter": "B", "minutes": 90 }
    ]
  },
  "M27_LRGB_H85": {
    "ra": "19h59.6m",
    "dec": "+22°43'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-06-15",
    "exposures": [
      { "filter": "L", "minutes": 100 },
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ]
  },
  "M51_LRGB_H85": {
    "ra": "13h29.9m",
    "dec": "+47°11'",
    "context": "Canes Venatici",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-05-14",
    "exposures": [
      { "filter": "L", "minutes": 780 },
      { "filter": "R", "minutes": 110 },
      { "filter": "G", "minutes": 110 },
      { "filter": "B", "minutes": 110 }
    ]
  },
  "M51_LRGB_gradient_H85": {
    "ra": "13h29.9m",
    "dec": "+47°11'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-05-14",
    "exposures": [
      { "filter": "L", "minutes": 780 },
      { "filter": "R", "minutes": 110 },
      { "filter": "G", "minutes": 110 },
      { "filter": "B", "minutes": 110 }
    ],
    "notes": [
      "with background gradient removed"
    ]
  },
  "M57_LRGB_H85": {
    "ra": "18h53.6m",
    "dec": "+33°02'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-06-10",
    "exposures": [
      { "filter": "L", "minutes": 30 },
      { "filter": "R", "minutes": 20 },
      { "filter": "G", "minutes": 20 },
      { "filter": "B", "minutes": 20 }
    ]
  },
  "M5_LRGB_H85": {
    "ra": "15h18.5m",
    "dec": "+02°04'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-05-14",
    "exposures": [
      { "filter": "L", "minutes": 120 },
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ]
  },
  "M63_LRGB_H85": {
    "ra": "13h15.8m",
    "dec": "+42°02'",
    "context": "Canes Venatici",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-03-15",
    "exposures": [
      { "filter": "L", "minutes": 900 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ]
  },
  "M74_LRGB_BBO": {
    "ra": "01h36.7m",
    "dec": "+15°47'",
    "context": "Pisces",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2006-12-24",
    "exposures": [
      { "filter": "L", "minutes": 300 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 36 },
      { "filter": "B", "minutes": 72 }
    ],
    "notes": [
      "joint imaging with Josch Hambsch"
    ]
  },
  "M74_LRGB_H85": {
    "ra": "01h36.7m",
    "dec": "+15°47'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-09-14",
    "exposures": [
      { "filter": "L", "minutes": 500 },
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ]
  },
  "M82_LRGBHa_H85": {
    "ra": "09h55.9m",
    "dec": "+69°40'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-02-05",
    "exposures": [
      { "filter": "L", "minutes": 140 },
      { "filter": "R", "minutes": 90 },
      { "filter": "G", "minutes": 90 },
      { "filter": "B", "minutes": 90 }
    ]
  },
  "M82_LRGB_H85": {
    "ra": "09h55.9m",
    "dec": "+69°40'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-02-05",
    "exposures": [
      { "filter": "L", "minutes": 140 },
      { "filter": "R", "minutes": 90 },
      { "filter": "G", "minutes": 90 },
      { "filter": "B", "minutes": 90 }
    ]
  },
  "M88_LRGB_H85": {
    "ra": "12h32.0m",
    "dec": "+14°25'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "M90_LRGB_BBO": {
    "ra": "12h36.8m",
    "dec": "+13°09'",
    "context": "Virgo",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-04-14",
    "exposures": [
      { "filter": "L", "minutes": 435 },
      { "filter": "R", "minutes": 120 },
      { "filter": "G", "minutes": 72 },
      { "filter": "B", "minutes": 108 }
    ]
  },
  "M95_LRGB_BBO": {
    "ra": "10h44.0m",
    "dec": "+11°42'",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-03-15",
    "exposures": [
      { "filter": "L", "minutes": 300 },
      { "filter": "R", "minutes": 90 },
      { "filter": "G", "minutes": 90 },
      { "filter": "B", "minutes": 90 }
    ]
  },
  "M95_LRGB_H85": {
    "ra": "10h44.0m",
    "dec": "+11°42'",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "NGC1156_RGB_H85": {
    "ra": "02h59.7m",
    "dec": "+25°14'",
    "context": "Aries",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "NGC2346_LRGB_H85": {
    "ra": "07h09.4m",
    "dec": "-00°48'",
    "context": "Monoceros",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-07-14",
    "exposures": [
      { "filter": "L", "minutes": 30 },
      { "filter": "R", "minutes": 15 },
      { "filter": "G", "minutes": 15 },
      { "filter": "B", "minutes": 15 }
    ]
  },
  "NGC253_LRGB_BBO": {
    "ra": "00h47.6m",
    "dec": "-25°17'",
    "context": "Sculptor",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-12-18",
    "exposures": [
      { "filter": "L", "minutes": 150 },
      { "filter": "R", "minutes": 45 },
      { "filter": "G", "minutes": 45 },
      { "filter": "B", "minutes": 45 }
    ]
  },
  "NGC2752_L_H85": {
    "ra": "09h05.7m",
    "dec": "+18°20'",
    "context": "Cancer",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-01-08",
    "exposures": [
      { "filter": "L", "minutes": 80 }
    ]
  },
  "NGC2903_LRGB_BBO": {
    "ra": "09h32.2m",
    "dec": "+21°30'",
    "context": "Leo",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-02-25",
    "exposures": [
      { "filter": "L", "minutes": 200 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ]
  },
  "NGC6181_L_H85": {
    "ra": "16h32.3m",
    "dec": "+19°50'",
    "context": "Hercules",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "NGC6826_LRGB_H85": {
    "ra": "19h44.8m",
    "dec": "+50°31'",
    "context": "Cygnus",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-07-06",
    "exposures": [
      { "filter": "L", "minutes": 20 },
      { "filter": "R", "minutes": 10 },
      { "filter": "G", "minutes": 10 },
      { "filter": "B", "minutes": 10 }
    ]
  },
  "NGC7331_LRGB_H85": {
    "ra": "22h37.1m",
    "dec": "+34°25'",
    "context": "Pegasus",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-09-26",
    "exposures": [
      { "filter": "L", "minutes": 400 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ]
  },
  "NGC7635_LRGB_BBO": {
    "ra": "23h20.7m",
    "dec": "+61°12'",
    "context": "Cassiopeia",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-10-12",
    "exposures": [
      { "filter": "L", "minutes": 120 },
      { "filter": "R", "minutes": 75 },
      { "filter": "G", "minutes": 45 },
      { "filter": "B", "minutes": 90 }
    ]
  },
  "NGC891_LRGB_BBO": {
    "ra": "02h22.6m",
    "dec": "+42°21'",
    "context": "Andromeda",
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-02-10",
    "exposures": [
      { "filter": "L", "minutes": 150 },
      { "filter": "R", "minutes": 45 },
      { "filter": "G", "minutes": 45 },
      { "filter": "B", "minutes": 45 }
    ]
  },
  "NGC891_LRGB_H85": {
    "ra": "02h22.6m",
    "dec": "+42°21'",
    "context": "Andromeda",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2004-10-12",
    "exposures": [
      { "filter": "L", "minutes": 100 },
      { "filter": "R", "minutes": 20 },
      { "filter": "G", "minutes": 20 },
      { "filter": "B", "minutes": 20 }
    ]
  },
  "NGC90_LRGB_H85": {
    "ra": "00h21.9m",
    "dec": "+22°25'",
    "context": "Andromeda",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2005-09-04",
    "exposures": [
      { "filter": "L", "minutes": 600 },
      { "filter": "R", "minutes": 120 },
      { "filter": "G", "minutes": 120 },
      { "filter": "B", "minutes": 120 }
    ]
  },
  "PK205_LRGB_BBO": {
    "telescope": "0.51-m f/8.26 Ritchey-Chrétien",
    "camera": "4008x2672 CCD",
    "date": "2007-02-24",
    "exposures": [
      { "filter": "L", "minutes": 200 },
      { "filter": "R", "minutes": 60 },
      { "filter": "G", "minutes": 60 },
      { "filter": "B", "minutes": 60 }
    ]
  },
  "SN2004eo_LRGB_H85": {
    "ra": "20h32.9m",
    "dec": "+09°56'",
    "context": "NGC 6928",
    "links": [
      { "label": "More on SN2004eo", "url": "http://www.astrosurf.com/snweb2/2004/04eo/04eoHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2004/04eo/04eoMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2004/04eo/04eoCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2004et_RGB_H85": {
    "ra": "20h35.4m",
    "dec": "+60°07'",
    "context": "NGC 6946",
    "links": [
      { "label": "More on SN2004et", "url": "http://www.astrosurf.com/snweb2/2004/04et/04etHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2004/04et/04etMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2004/04et/04etCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2004fu_RGB_H85": {
    "ra": "20h35.2m",
    "dec": "+64°48'",
    "context": "NGC 6949",
    "links": [
      { "label": "More on SN2004fu", "url": "http://www.astrosurf.com/snweb2/2004/04fu/04fuHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2004/04fu/04fuMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2004/04fu/04fuCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2004gq_RGB_H85": {
    "ra": "05h12.1m",
    "dec": "-15°41'",
    "context": "NGC 1832",
    "links": [
      { "label": "More on SN2004gq", "url": "http://www.astrosurf.com/snweb2/2004/04gq/04gqHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2004/04gq/04gqMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2004/04gq/04gqCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005A_RGB_H85": {
    "ra": "02h30.7m",
    "dec": "-02°56'",
    "context": "NGC 958",
    "links": [
      { "label": "More on SN2005A", "url": "http://www.astrosurf.com/snweb2/2005/05A_/05A_Home.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05A_/05A_Meas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05A_/05A_Curv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005W_RGB_H85": {
    "ra": "01h50.8m",
    "dec": "+21°46'",
    "context": "NGC 691",
    "links": [
      { "label": "More on SN2005W", "url": "http://www.astrosurf.com/snweb2/2005/05W_/05W_Home.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05W_/05W_Meas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05W_/05W_Curv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005am_RGB_H85": {
    "ra": "09h16.2m",
    "dec": "-16°18'",
    "context": "NGC 2811",
    "links": [
      { "label": "More on SN2005am", "url": "http://www.astrosurf.com/snweb2/2005/05am/05amHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05am/05amMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05am/05amCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005ay_RGB_H85": {
    "ra": "11h52.8m",
    "dec": "+44°06'",
    "context": "NGC 3938",
    "links": [
      { "label": "More on SN2005ay", "url": "http://www.astrosurf.com/snweb2/2005/05ay/05ayHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05ay/05ayMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05ay/05ayCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005cs_RGB_H85": {
    "ra": "13h29.9m",
    "dec": "+47°11'",
    "context": "NGC 5194",
    "links": [
      { "label": "More on SN2005cs", "url": "http://www.astrosurf.com/snweb2/2005/05cs/05csHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05cs/05csMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05cs/05csCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005da_RGB_H85": {
    "ra": "18h37.8m",
    "dec": "+17°33'",
    "context": "UGC 11301",
    "links": [
      { "label": "More on SN2005da", "url": "http://www.astrosurf.com/snweb2/2005/05da/05daHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05da/05daMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05da/05daCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2005de_RGB_H85": {
    "ra": "18h02.4m",
    "dec": "+26°03'",
    "context": "UGC 11097",
    "links": [
      { "label": "More on SN2005de", "url": "http://www.astrosurf.com/snweb2/2005/05de/05deHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2005/05de/05deMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2005/05de/05deCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD"
  },
  "SN2008ax_LRGB_H85": {
    "ra": "12h30.7m",
    "dec": "+41°38'",
    "context": "NGC 4490",
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2008-04-02",
    "exposures": [
      { "filter": "L", "minutes": 30 },
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ],
    "links": [
      { "label": "More on SN2008ax", "url": "http://www.astrosurf.com/snweb2/2008/08ax/08axHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2008/08ax/08axMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2008/08ax/08axCurv.htm" }
    ]
  },
  "SN2008bo_LRGB_H85": {
    "ra": "18h19.9m",
    "dec": "+74°34'",
    "context": "NGC 6643",
    "links": [
      { "label": "More on SN2008bo", "url": "http://www.astrosurf.com/snweb2/2008/08bo/08boHome.htm" },
      { "label": "Measures", "url": "http://www.astrosurf.com/snweb2/2008/08bo/08boMeas.htm" },
      { "label": "Curves", "url": "http://www.astrosurf.com/snweb2/2008/08bo/08boCurv.htm" }
    ],
    "telescope": "0.45-m f/7.25 Ritchey-Chrétien",
    "camera": "3072x2048 CCD",
    "date": "2008-04-02",
    "exposures": [
      { "filter": "L", "minutes": 30 },
      { "filter": "R", "minutes": 30 },
      { "filter": "G", "minutes": 30 },
      { "filter": "B", "minutes": 30 }
    ]
  }
};
